### ISSUE TITLE
`@sentry/profiling-node` fails at postinstall step of `GLIBCXX` in Vercel deployment

### ISSUE THREAD

**Issue by mcmxcdev** [getsentry/profiling-node#93]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/sentry-javascript/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/sentry-javascript/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### Which package are you using?

@sentry/nextjs

### SDK Version

7.33.0

### Framework Version

Nextjs 13.1.2 with React v18.2.0

### SDK Setup

```javascript

import * as Sentry from '@sentry/node';
import { ProfilingIntegration } from '@sentry/profiling-node';
import '@sentry/tracing';

Sentry.init({
    dsn: process.env.SENTRY_DSN_MONOLITH,
    environment: process.env.ENVIRONMENT_NAME,
    integrations: [new ProfilingIntegration()],
    profilesSampleRate: 1,
})
```

### Steps to Reproduce

1. set up project with `@sentry/profiling-node`
1. run build using Vercel with Node v18
2. expect error to pop up

### Expected Result

`@sentry/profiling-node` installs just fine

### Actual Result

Vercel deployment logs

```
Cloning github.com/org/repo (Branch: feat/improvements-to-sentry-setup, Commit: 19f438e)
Cloning completed: 991.537ms
Running "git diff HEAD^ HEAD --quiet ./apps/app"
Restored build cache
Running "vercel build"
Vercel CLI 28.13.0
Detected ENABLE_EXPERIMENTAL_COREPACK=1 and "pnpm@7.25.0" in package.json
Installing dependencies...
Scope: all 5 workspace projects
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +20 -19
++++++++++++++++++++-------------------
Progress: resolved 20, reused 0, downloaded 9, added 8
Progress: resolved 20, reused 0, downloaded 20, added 20, done
.../node_modules/@sentry/profiling-node install$ node scripts/empty.js
.../node_modules/@sentry/profiling-node install: Done
.../node_modules/@sentry/profiling-node postinstall$ node scripts/check-build.js
.../node_modules/@sentry/profiling-node postinstall: /vercel/path0/node_modules/.pnpm/@sentry+profiling-node@0.0.13/node_modules/@sentry/profiling-node/scripts/check-build.js:43
.../node_modules/@sentry/profiling-node postinstall:   throw e;
.../node_modules/@sentry/profiling-node postinstall:   ^
.../node_modules/@sentry/profiling-node postinstall: Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /vercel/path0/node_modules/.pnpm/@sentry+profiling-node@0.0.13/node_modules/@sentry/profiling-node/binaries/sentry_cpu_profiler-v108-linux-x64.node)
.../node_modules/@sentry/profiling-node postinstall:     at Module._extensions..node (node:internal/modules/cjs/loader:1243:18)
.../node_modules/@sentry/profiling-node postinstall:     at Module.load (node:internal/modules/cjs/loader:1037:32)
.../node_modules/@sentry/profiling-node postinstall:     at Module._load (node:internal/modules/cjs/loader:878:12)
.../node_modules/@sentry/profiling-node postinstall:     at Module.require (node:internal/modules/cjs/loader:1061:19)
.../node_modules/@sentry/profiling-node postinstall:     at require (node:internal/modules/cjs/helpers:103:18)
.../node_modules/@sentry/profiling-node postinstall:     at Object.<anonymous> (/vercel/path0/node_modules/.pnpm/@sentry+profiling-node@0.0.13/node_modules/@sentry/profiling-node/scripts/check-build.js:23:3)
.../node_modules/@sentry/profiling-node postinstall:     at Module._compile (node:internal/modules/cjs/loader:1159:14)
.../node_modules/@sentry/profiling-node postinstall:     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
.../node_modules/@sentry/profiling-node postinstall:     at Module.load (node:internal/modules/cjs/loader:1037:32)
.../node_modules/@sentry/profiling-node postinstall:     at Module._load (node:internal/modules/cjs/loader:878:12) {
.../node_modules/@sentry/profiling-node postinstall:   code: 'ERR_DLOPEN_FAILED'
.../node_modules/@sentry/profiling-node postinstall: }
.../node_modules/@sentry/profiling-node postinstall: Node.js v18.12.1
.../node_modules/@sentry/profiling-node postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1.
Error: Command "pnpm install" exited with 1
```

**Comment by bjankord** [comment]
Running into a very similar error on our Jenkins box related to the binary unable to access `GLIBCXX_3.4.29'.

**Comment by JonasBa** [comment]
@bjankord I will be merging https://github.com/getsentry/profiling-node/pull/92 and making a release in the coming days that should hopefully fix htis

**Comment by bjankord** [comment]
Thanks @JonasBa, we are running the app on node v16.19.0 on a linux_x64 image.

**Comment by dialexo** [comment]
Piggybacking this thread, we're having the same issue on a Github Actions workflow performing a Docker build of our Node application (see run fail here https://github.com/graasp/graasp/actions/runs/4045490336/jobs/6957795511#step:6:5932).

I've tried replicating this locally: this does not affect the build on MacOS Ventura 13.1 (i guess the dependency is bundled with the xcode CL tools maybe). However on a Linux machine (Ubuntu 18.04) I get the same error and the logs read the same message as above:

```
# This file contains the result of Yarn building a package (@sentry/profiling-node@npm:0.0.13)
   2   │ # Script name: postinstall
   3   │ 
   4   │ /home/user/graasp/graasp/node_modules/@sentry/profiling-node/scripts/check-build.js:43
   5   │   throw e;
   6   │   ^
   7   │ 
   8   │ Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/user
       │ /graasp/graasp/node_modules/@sentry/profiling-node/binaries/sentry_cpu_profiler-v93-linux-x64.node)
   9   │     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1183:18)
  10   │     at Module.load (node:internal/modules/cjs/loader:981:32)
  11   │     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
  12   │     at Module.require (node:internal/modules/cjs/loader:1005:19)
  13   │     at require (node:internal/modules/cjs/helpers:102:18)
  14   │     at Object.<anonymous> (/home/user/graasp/graasp/node_modules/@sentry/profiling-node/scripts/check-b
       │ uild.js:23:3)
  15   │     at Module._compile (node:internal/modules/cjs/loader:1101:14)
  16   │     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
  17   │     at Module.load (node:internal/modules/cjs/loader:981:32)
  18   │     at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  19   │   code: 'ERR_DLOPEN_FAILED'
  20   │ }
```

We're using [this Dockerfile](https://github.com/graasp/graasp/blob/master/.stagingcontainer/Dockerfile) so `node:16` as base.

**Comment by JonasBa** [comment]
Thanks for sharing @dialexo, I'm preparing a release soon that should address this

**Comment by JonasBa** [comment]
@dialexo @dustin-decker and @bjankord, does the module compile if you downgrade to 0.0.12?

**Comment by dustin-decker** [comment]
It appears to compile on 0.0.12 but I have not tested it beyond that yet.

**Comment by JonasBa** [comment]
Ok yeah, that version works because it ships without precompiled binaries so you end up always building from source.

**Comment by timfish** [comment]
I've had similar glibc versions errors with native node modules and it's usually been solved by compiling the prebuilt binaries on the oldest ubuntu version available for better compatibility. Up until this month that would have been `ubuntu-18.04` but now that has been deprecated you'd have to use `ubuntu-20.04`.

**Comment by JonasBa** [comment]
Yeah, great point @timfish. I suspect part of the problem was also that we namespaced binaries only based on arch, I added libc to that as well so we can tell between musl/glibc.

And yeah, we currently just build on 22.04, but it's a good point to downgrade to 20.04. I'm currently trying to run the prebuilt binaries on docker images by just referencing a github commit as the npm dep where all the binaries are checked in and so far it seems run without errors. I'm tempted to run a release and see if we need to downgrade to 20.04

**Comment by bjankord** [comment]
@JonasBa I was able to run our build on Jenkins with our linux image using @sentry/profiling-node v0.0.12. 
Thanks for the tip on that, looking forward to the next release!

**Comment by JonasBa** [comment]
We just released 0.1.0-alpha.1 which should address this. I'm going to keep the issue open until we can confirm it's resolved. If you have a second and want to try upgrading, it would be greatly appreciated. We will promote to minor version once we can make sure we fixed the issue with the binaries.

**Comment by JonasBa** [comment]
Seems like the issue persists on vercel/next, I will try downgrading the ubuntu images to 20.04 (I'm actually not even sure what env next runs in and it doesn't seem documented)

**Comment by JonasBa** [comment]
@timfish was correct - downgrading to ubuntu 20.04 passes vercel build. I'll create a new release with prebuilt binaries on ubuntu 20.04

**Comment by bjankord** [comment]
Just tried the v0.1.0-alpha.1 release and ran into this error:
```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /hYour_Watch_Your_Way_master/node_modules/@sentry/profiling-node/binaries/sentry_cpu_profiler-v93-linux-x64-glibc.node)
```
Curious @JonasBa if we can get a v0.1.0-alpha.2 release to test out the downgrade to ubuntu 20.04?

**Comment by JonasBa** [comment]
@bjankord yes, we will do a release today (I manually verified it by referencing a github commit as the npm dependency). I will post here once the release is out

**Comment by JonasBa** [comment]
@bjankord 0.1.0-alpha.2 has been released

**Comment by bjankord** [comment]
@JonasBa Thank you, I'll go test that in our build pipeline and let you know how works out.

**Comment by bjankord** [comment]
@JonasBa 0.1.0-alpha.2 worked, thanks for the quick triage on this issue, much appreciated!

**Comment by JonasBa** [comment]
@bjankord thanks so much, I will start the release of 0.1.0 🎉

**Comment by JonasBa** [comment]
0.1.0 has been released, thanks everyone for your patience 🙏🏼
